
CREATE SEQUENCE "TRADE_DB_ID_seq";
CREATE TABLE "TRADE"(
    "DB_ID" BIGINT NOT NULL  DEFAULT nextval('"TRADE_DB_ID_seq"'),
    "ASSET_ID" BIGINT NOT NULL,
    "BLOCK_ID" BIGINT NOT NULL,
    "ASK_ORDER_ID" BIGINT NOT NULL,
    "BID_ORDER_ID" BIGINT NOT NULL,
    "ASK_ORDER_HEIGHT" INTEGER NOT NULL,
    "BID_ORDER_HEIGHT" INTEGER NOT NULL,
    "SELLER_ID" BIGINT NOT NULL,
    "BUYER_ID" BIGINT NOT NULL,
    "IS_BUY" BOOLEAN NOT NULL,
    "QUANTITY" BIGINT NOT NULL,
    "PRICE" BIGINT NOT NULL,
    "TIMESTAMP" INTEGER NOT NULL,
    "HEIGHT" INTEGER NOT NULL,
    PRIMARY KEY ("DB_ID")
);
CREATE INDEX "TRADE_ASK_IDX" ON "TRADE" ("ASK_ORDER_ID", "HEIGHT");
CREATE INDEX "TRADE_ASSET_ID_IDX" ON "TRADE" ("ASSET_ID", "HEIGHT");
CREATE INDEX "TRADE_BID_IDX" ON "TRADE" ("BID_ORDER_ID", "HEIGHT");
CREATE INDEX "TRADE_BUYER_ID_IDX" ON "TRADE" ("BUYER_ID", "HEIGHT");
CREATE INDEX "TRADE_HEIGHT_DB_ID_IDX" ON "TRADE" ("HEIGHT", "DB_ID");
CREATE INDEX "TRADE_HEIGHT_IDX" ON "TRADE" ("HEIGHT");
CREATE INDEX "TRADE_SELLER_ID_IDX" ON "TRADE" ("SELLER_ID", "HEIGHT");

CREATE SEQUENCE "ASSET_DB_ID_seq";
CREATE TABLE "ASSET"(
    "DB_ID" BIGINT NOT NULL  DEFAULT nextval('"ASSET_DB_ID_seq"'),
    "ID" BIGINT NOT NULL,
    "ACCOUNT_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "QUANTITY" BIGINT NOT NULL,
    "DECIMALS" SMALLINT NOT NULL,
    "INITIAL_QUANTITY" BIGINT NOT NULL,
    "HEIGHT" INTEGER NOT NULL,
    "LATEST" BOOLEAN DEFAULT 'TRUE' NOT NULL,
    PRIMARY KEY ("DB_ID")
);
CREATE UNIQUE INDEX "ASSET_ID_HEIGHT_IDX" ON "ASSET" ("ID", "HEIGHT");
CREATE INDEX "ASSET_ACCOUNT_ID_IDX" ON "ASSET" ("ACCOUNT_ID");
CREATE INDEX "ASSET_HEIGHT_ID_IDX" ON "ASSET" ("HEIGHT", "ID");



CREATE SEQUENCE "BLOCK_DB_ID_seq";
CREATE TABLE "BLOCK"(
    "DB_ID" BIGINT NOT NULL  DEFAULT nextval('"BLOCK_DB_ID_seq"'),
    "ID" BIGINT NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "TIMESTAMP" INTEGER NOT NULL,
    "PREVIOUS_BLOCK_ID" BIGINT,
    "TOTAL_AMOUNT" BIGINT NOT NULL,
    "TOTAL_FEE" BIGINT NOT NULL,
    "PAYLOAD_LENGTH" INTEGER NOT NULL,
    "PREVIOUS_BLOCK_HASH" BYTEA,
    "CUMULATIVE_DIFFICULTY" BYTEA NOT NULL,
    "BASE_TARGET" BIGINT NOT NULL,
    "NEXT_BLOCK_ID" BIGINT,
    "HEIGHT" INTEGER NOT NULL,
    "GENERATION_SIGNATURE" BYTEA NOT NULL,
    "BLOCK_SIGNATURE" BYTEA NOT NULL,
    "PAYLOAD_HASH" BYTEA NOT NULL,
    "GENERATOR_ID" BIGINT NOT NULL,
    PRIMARY KEY ("DB_ID")
);
CREATE UNIQUE INDEX "BLOCK_HEIGHT_IDX" ON "BLOCK" ("HEIGHT");
CREATE UNIQUE INDEX "BLOCK_ID_IDX" ON "BLOCK" ("ID");
CREATE UNIQUE INDEX "BLOCK_TIMESTAMP_IDX" ON "BLOCK" ("TIMESTAMP");
CREATE INDEX "BLOCK_GENERATOR_ID_IDX" ON "BLOCK" ("GENERATOR_ID");

CREATE SEQUENCE "TRANSACTION_DB_ID_seq";
CREATE TABLE "TRANSACTION"(
    "DB_ID" BIGINT NOT NULL  DEFAULT nextval('"TRANSACTION_DB_ID_seq"'),
    "ID" BIGINT NOT NULL,
    "DEADLINE" SMALLINT NOT NULL,
    "RECIPIENT_ID" BIGINT,
    "AMOUNT" BIGINT NOT NULL,
    "FEE" BIGINT NOT NULL,
    "FULL_HASH" BYTEA NOT NULL,
    "HEIGHT" INTEGER NOT NULL,
    "BLOCK_ID" BIGINT NOT NULL,
    "SIGNATURE" BYTEA NOT NULL,
    "TIMESTAMP" INTEGER NOT NULL,
    "TYPE" SMALLINT NOT NULL,
    "SUBTYPE" SMALLINT NOT NULL,
    "SENDER_ID" BIGINT NOT NULL,
    "BLOCK_TIMESTAMP" INTEGER NOT NULL,
    "REFERENCED_TRANSACTION_FULL_HASH" BYTEA,
    "TRANSACTION_INDEX" SMALLINT NOT NULL,
    "PHASED" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "ATTACHMENT_BYTES" BYTEA,
    "VERSION" SMALLINT NOT NULL,
    "HAS_MESSAGE" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "HAS_ENCRYPTED_MESSAGE" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "HAS_PUBLIC_KEY_ANNOUNCEMENT" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "HAS_PRUNABLE_MESSAGE" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "HAS_PRUNABLE_ATTACHMENT" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "EC_BLOCK_HEIGHT" INTEGER DEFAULT NULL,
    "EC_BLOCK_ID" BIGINT DEFAULT NULL,
    "HAS_ENCRYPTTOSELF_MESSAGE" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    "HAS_PRUNABLE_ENCRYPTED_MESSAGE" BOOLEAN DEFAULT 'FALSE' NOT NULL,
    PRIMARY KEY ("DB_ID")
);
CREATE UNIQUE INDEX "TRANSACTION_ID_IDX" ON "TRANSACTION" ("ID");
CREATE INDEX "TRANSACTION_BLOCK_TIMESTAMP_IDX" ON "TRANSACTION" ("BLOCK_TIMESTAMP");
CREATE INDEX "TRANSACTION_RECIPIENT_ID_IDX" ON "TRANSACTION" ("RECIPIENT_ID");
CREATE INDEX "TRANSACTION_SENDER_ID_IDX" ON "TRANSACTION" ("SENDER_ID");
ALTER TABLE "TRANSACTION"
    ADD CONSTRAINT "CONSTRAINT_FF" FOREIGN KEY ("BLOCK_ID") REFERENCES "BLOCK" ("ID");
