
-- CREATE TABLE BLOCK(
--     DB_ID BIGINT AUTO_INCREMENT NOT NULL,
--     ID BIGINT NOT NULL,
--     VERSION INTEGER NOT NULL,
--     TIMESTAMP INTEGER NOT NULL,
--     PREVIOUS_BLOCK_ID BIGINT,
--     TOTAL_AMOUNT BIGINT NOT NULL,
--     TOTAL_FEE BIGINT NOT NULL,
--     PAYLOAD_LENGTH INTEGER NOT NULL,
--     PREVIOUS_BLOCK_HASH VARBINARY(32) NULL,
--     CUMULATIVE_DIFFICULTY VARBINARY(8000) NOT NULL,
--     BASE_TARGET BIGINT NOT NULL,
--     NEXT_BLOCK_ID BIGINT,
--     HEIGHT INTEGER NOT NULL,
--     GENERATION_SIGNATURE VARBINARY(64) NOT NULL,
--     BLOCK_SIGNATURE VARBINARY(64) NOT NULL,
--     PAYLOAD_HASH VARBINARY(32) NOT NULL,
--     GENERATOR_ID BIGINT NOT NULL,
--     PRIMARY KEY (DB_ID)
-- );
-- CREATE UNIQUE INDEX BLOCK_HEIGHT_IDX ON BLOCK (HEIGHT);
-- CREATE UNIQUE INDEX BLOCK_ID_IDX ON BLOCK (ID);
-- CREATE UNIQUE INDEX BLOCK_TIMESTAMP_IDX ON BLOCK (TIMESTAMP);
-- CREATE INDEX BLOCK_GENERATOR_ID_IDX ON BLOCK (GENERATOR_ID);

CREATE TABLE TRANSACTION(
    DB_ID BIGINT NOT NULL AUTO_INCREMENT,
    ID BIGINT NOT NULL,
    DEADLINE SMALLINT NOT NULL,
    RECIPIENT_ID BIGINT,
    AMOUNT BIGINT NOT NULL,
    FEE BIGINT NOT NULL,
    FULL_HASH VARBINARY(32) NOT NULL,
    HEIGHT INTEGER NOT NULL,
    BLOCK_ID BIGINT NOT NULL,
    SIGNATURE VARBINARY(64) NOT NULL,
    TIMESTAMP INTEGER NOT NULL,
    TYPE TINYINT NOT NULL,
    SUBTYPE TINYINT NOT NULL,
    SENDER_ID BIGINT NOT NULL,
    BLOCK_TIMESTAMP INTEGER NOT NULL,
    REFERENCED_TRANSACTION_FULL_HASH VARBINARY(32) NULL,
    TRANSACTION_INDEX SMALLINT NOT NULL,
    PHASED BOOLEAN DEFAULT FALSE NOT NULL,
    ATTACHMENT_BYTES VARBINARY(8000) NULL,
    VERSION TINYINT NOT NULL,
    HAS_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
    HAS_ENCRYPTED_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
    HAS_PUBLIC_KEY_ANNOUNCEMENT BOOLEAN DEFAULT FALSE NOT NULL,
    HAS_PRUNABLE_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
    HAS_PRUNABLE_ATTACHMENT BOOLEAN DEFAULT FALSE NOT NULL,
    EC_BLOCK_HEIGHT INTEGER DEFAULT NULL,
    EC_BLOCK_ID BIGINT DEFAULT NULL,
    HAS_ENCRYPTTOSELF_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
    HAS_PRUNABLE_ENCRYPTED_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (DB_ID)
);
CREATE UNIQUE INDEX TRANSACTION_ID_IDX ON TRANSACTION (ID);
-- CREATE INDEX TRANSACTION_BLOCK_TIMESTAMP_IDX ON TRANSACTION (BLOCK_TIMESTAMP);
CREATE INDEX TRANSACTION_RECIPIENT_ID_IDX ON TRANSACTION (RECIPIENT_ID);
CREATE INDEX TRANSACTION_SENDER_ID_IDX ON TRANSACTION (SENDER_ID);
-- ALTER TABLE TRANSACTION
--     ADD CONSTRAINT CONSTRAINT_FF FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK (ID);

CREATE TABLE TRADE(
    DB_ID BIGINT NOT NULL AUTO_INCREMENT,
    ASSET_ID BIGINT NOT NULL,
    BLOCK_ID BIGINT NOT NULL,
    ASK_ORDER_ID BIGINT NOT NULL,
    BID_ORDER_ID BIGINT NOT NULL,
    ASK_ORDER_HEIGHT INTEGER NOT NULL,
    BID_ORDER_HEIGHT INTEGER NOT NULL,
    SELLER_ID BIGINT NOT NULL,
    BUYER_ID BIGINT NOT NULL,
    IS_BUY BOOLEAN NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PRICE BIGINT NOT NULL,
    TIMESTAMP INTEGER NOT NULL,
    HEIGHT INTEGER NOT NULL,
    PRIMARY KEY (DB_ID)
);
CREATE INDEX TRADE_ASK_IDX ON TRADE (ASK_ORDER_ID, HEIGHT);
CREATE INDEX TRADE_ASSET_ID_IDX ON TRADE (ASSET_ID, HEIGHT);
CREATE INDEX TRADE_BID_IDX ON TRADE (BID_ORDER_ID, HEIGHT);
CREATE INDEX TRADE_BUYER_ID_IDX ON TRADE (BUYER_ID, HEIGHT);
CREATE INDEX TRADE_HEIGHT_DB_ID_IDX ON TRADE (HEIGHT, DB_ID);
CREATE INDEX TRADE_HEIGHT_IDX ON TRADE (HEIGHT);
CREATE INDEX TRADE_SELLER_ID_IDX ON TRADE (SELLER_ID, HEIGHT);

CREATE TABLE ASSET(
    DB_ID BIGINT NOT NULL AUTO_INCREMENT,
    ID BIGINT NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    QUANTITY BIGINT NOT NULL,
    DECIMALS TINYINT NOT NULL,
    INITIAL_QUANTITY BIGINT NOT NULL,
    HEIGHT INTEGER NOT NULL,
    LATEST BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (DB_ID)
);
CREATE UNIQUE INDEX ASSET_ID_HEIGHT_IDX ON ASSET (ID, HEIGHT);
CREATE INDEX ASSET_ACCOUNT_ID_IDX ON ASSET (ACCOUNT_ID);
CREATE INDEX ASSET_HEIGHT_ID_IDX ON ASSET (HEIGHT, ID);

CREATE TABLE ACCOUNT_LEDGER(
    DB_ID BIGINT NOT NULL AUTO_INCREMENT,
    ACCOUNT_ID BIGINT NOT NULL,
    EVENT_TYPE TINYINT NOT NULL,
    EVENT_ID BIGINT NOT NULL,
    HOLDING_TYPE TINYINT NOT NULL,
    HOLDING_ID BIGINT,
    `CHANGE` BIGINT NOT NULL,
    BALANCE BIGINT NOT NULL,
    BLOCK_ID BIGINT NOT NULL,
    HEIGHT INTEGER NOT NULL,
    TIMESTAMP INTEGER NOT NULL,
    PRIMARY KEY (DB_ID)
);
CREATE INDEX ACCOUNT_LEDGER_HEIGHT_IDX ON ACCOUNT_LEDGER (HEIGHT);
CREATE INDEX ACCOUNT_LEDGER_ID_IDX ON ACCOUNT_LEDGER (ACCOUNT_ID, DB_ID);
